"""Token constants."""
# Auto-generated by Tools/scripts/generate_token.py

__all__ = ['tok_name', 'ISTERMINAL', 'ISNONTERMINAL', 'ISEOF']

ENDMARKER = 0
NAME = 1
NUMBER = 2
STRING = 3
NEWLINE = 4
INDENT = 5
DEDENT = 6
LPAR = 7
RPAR = 8
LSQB = 9
RSQB = 10
COLON = 11
COMMA = 12
SEMI = 13
PLUS = 14
NEWPLUS = 15
MINUS = 16
STAR = 17
SLASH = 18
VBAR = 19
AMPER = 20
LESS = 21
GREATER = 22
NEWEQUAL = 23
EQUAL = 24
DOT = 25
PERCENT = 26
LBRACE = 27
RBRACE = 28
EQEQUAL = 29
NOTEQUAL = 30
LESSEQUAL = 31
GREATEREQUAL = 32
TILDE = 33
CIRCUMFLEX = 34
LEFTSHIFT = 35
RIGHTSHIFT = 36
DOUBLESTAR = 37
PLUSEQUAL = 38
MINEQUAL = 39
STAREQUAL = 40
SLASHEQUAL = 41
PERCENTEQUAL = 42
AMPEREQUAL = 43
VBAREQUAL = 44
CIRCUMFLEXEQUAL = 45
LEFTSHIFTEQUAL = 46
RIGHTSHIFTEQUAL = 47
DOUBLESTAREQUAL = 48
DOUBLESLASH = 49
DOUBLESLASHEQUAL = 50
AT = 51
ATEQUAL = 52
RARROW = 53
ELLIPSIS = 54
COLONEQUAL = 55
OP = 56
AWAIT = 57
ASYNC = 58
TYPE_IGNORE = 59
TYPE_COMMENT = 60
SOFT_KEYWORD = 61
# These aren't used by the C tokenizer but are needed for tokenize.py
ERRORTOKEN = 62
COMMENT = 63
NL = 64
ENCODING = 65
N_TOKENS = 66
# Special definitions for cooperation with parser
NT_OFFSET = 256

tok_name = {value: name
            for name, value in globals().items()
            if isinstance(value, int) and not name.startswith('_')}
__all__.extend(tok_name.values())

EXACT_TOKEN_TYPES = {
    '!=': NOTEQUAL,
    '%': PERCENT,
    '%=': PERCENTEQUAL,
    '&': AMPER,
    '&=': AMPEREQUAL,
    '(': LPAR,
    ')': RPAR,
    '*': STAR,
    '**': DOUBLESTAR,
    '**=': DOUBLESTAREQUAL,
    '*=': STAREQUAL,
    '+': PLUS,
    '+=': PLUSEQUAL,
    ',': COMMA,
    '-': MINUS,
    '-=': MINEQUAL,
    '->': RARROW,
    '.': DOT,
    '..': NEWEQUAL,
    '...': ELLIPSIS,
    '/': SLASH,
    '//': DOUBLESLASH,
    '//=': DOUBLESLASHEQUAL,
    '/=': SLASHEQUAL,
    ':': COLON,
    ':=': COLONEQUAL,
    ';': SEMI,
    '<': LESS,
    '<<': LEFTSHIFT,
    '<<=': LEFTSHIFTEQUAL,
    '<=': LESSEQUAL,
    '=': EQUAL,
    '==': EQEQUAL,
    '>': GREATER,
    '>=': GREATEREQUAL,
    '>>': RIGHTSHIFT,
    '>>=': RIGHTSHIFTEQUAL,
    '@': AT,
    '@=': ATEQUAL,
    '[': LSQB,
    ']': RSQB,
    '^': CIRCUMFLEX,
    '^=': CIRCUMFLEXEQUAL,
    '{': LBRACE,
    '|': VBAR,
    '|=': VBAREQUAL,
    '}': RBRACE,
    '~': TILDE,
}

def ISTERMINAL(x):
    return x < NT_OFFSET

def ISNONTERMINAL(x):
    return x >= NT_OFFSET

def ISEOF(x):
    return x == ENDMARKER
