/* Auto-generated by Tools/scripts/generate_token.py */

/* Token types */
#ifndef Py_LIMITED_API
#ifndef Py_TOKEN_H
#define Py_TOKEN_H
#ifdef __cplusplus
extern "C" {
#endif

#undef TILDE   /* Prevent clash of our definition with system macro. Ex AIX, ioctl.h */

#define ENDMARKER       0
#define NAME            1
#define NUMBER          2
#define STRING          3
#define NEWLINE         4
#define INDENT          5
#define DEDENT          6
#define LPAR            7
#define RPAR            8
#define LSQB            9
#define RSQB            10
#define COLON           11
#define COMMA           12
#define SEMI            13
#define PLUS            14
#define NEWPLUS         15
#define MINUS           16
#define STAR            17
#define SLASH           18
#define VBAR            19
#define AMPER           20
#define LESS            21
#define GREATER         22
#define NEWEQUAL        23
#define EQUAL           24
#define DOT             25
#define PERCENT         26
#define LBRACE          27
#define RBRACE          28
#define EQEQUAL         29
#define NOTEQUAL        30
#define LESSEQUAL       31
#define GREATEREQUAL    32
#define TILDE           33
#define CIRCUMFLEX      34
#define LEFTSHIFT       35
#define RIGHTSHIFT      36
#define DOUBLESTAR      37
#define PLUSEQUAL       38
#define MINEQUAL        39
#define STAREQUAL       40
#define SLASHEQUAL      41
#define PERCENTEQUAL    42
#define AMPEREQUAL      43
#define VBAREQUAL       44
#define CIRCUMFLEXEQUAL 45
#define LEFTSHIFTEQUAL  46
#define RIGHTSHIFTEQUAL 47
#define DOUBLESTAREQUAL 48
#define DOUBLESLASH     49
#define DOUBLESLASHEQUAL 50
#define AT              51
#define ATEQUAL         52
#define RARROW          53
#define ELLIPSIS        54
#define COLONEQUAL      55
#define OP              56
#define AWAIT           57
#define ASYNC           58
#define TYPE_IGNORE     59
#define TYPE_COMMENT    60
#define SOFT_KEYWORD    61
#define ERRORTOKEN      62
#define N_TOKENS        66
#define NT_OFFSET       256

/* Special definitions for cooperation with parser */

#define ISTERMINAL(x)           ((x) < NT_OFFSET)
#define ISNONTERMINAL(x)        ((x) >= NT_OFFSET)
#define ISEOF(x)                ((x) == ENDMARKER)
#define ISWHITESPACE(x)         ((x) == ENDMARKER || \
                                 (x) == NEWLINE   || \
                                 (x) == INDENT    || \
                                 (x) == DEDENT)


PyAPI_DATA(const char * const) _PyParser_TokenNames[]; /* Token names */
PyAPI_FUNC(int) PyToken_OneChar(int);
PyAPI_FUNC(int) PyToken_TwoChars(int, int);
PyAPI_FUNC(int) PyToken_ThreeChars(int, int, int);

#ifdef __cplusplus
}
#endif
#endif /* !Py_TOKEN_H */
#endif /* Py_LIMITED_API */
